env:
  CIRRUS_SHELL: bash

build_task:
  skip: $CIRRUS_BRANCH == "public_master"
  container:
    dockerfile: .cirrus/Dockerfile
    cpu: 2
    memory: 4G
  env:
    SONAR_HOST_URL: https://sonarcloud.io
    SONAR_TOKEN: ENCRYPTED[!7a28d43095ea7e33c5e581fa3a6592ed0ac609d512213590cf41ce096e0849f360eb2f0881d7728f30cb148bed866ca5!]
    GRADLE_USER_HOME: ${CIRRUS_WORKING_DIR}/.gradle
    GOPATH: ${HOME}/go
  gradle_cache:
    folder: .gradle/caches
    fingerprint_script: find -type f \( -name "*.gradle*" -or -name "gradle*.properties" \) | sort | xargs cat
  go_cache:
    folder: ${HOME}/go
  script:
    - ./build.sh
  cleanup_gradle_script:
    - /usr/bin/find "${CIRRUS_WORKING_DIR}/.gradle/caches/" -name "*.lock" -type f -delete
    - rm -rf "${CIRRUS_WORKING_DIR}/.gradle/caches/7.*/"
    - rm -rf "${CIRRUS_WORKING_DIR}/.gradle/caches/journal-1/"
