name: Unified Dogfooding scans
on:
  schedule:
    - cron: '0 4 * * 1-5' # Run Mon-Fri at 04:00 UTC
  workflow_dispatch:

jobs:
  analyze:
    runs-on: warp-custom-ubuntu-24-04
    name: Build and Analyze on all platforms
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
        with:
          version: 2025.7.12
      - uses: SonarSource/ci-github-actions/build-gradle@v1
        with:
          run-shadow-scans: true
          use-develocity: true
          deploy-pull-request: false
          gradle-args: "-Dsonar.organization=sonarsource"
      - name: Run IRIS Sync
        uses: SonarSource/unified-dogfooding-actions/run-iris@v1
        with:
          primary_project_key: "org.sonarsource.slang:slang"
          primary_platform: "Next"
          shadow1_project_key: "org.sonarsource.slang:slang"
          shadow1_platform: "SQC-EU"
          shadow2_project_key: "org.sonarsource.slang:slang"
          shadow2_platform: "SQC-US"
